### ISSUE TITLE
This URL 404's

### ISSUE THREAD

**Issue by hbiede** [cbourke/CSCE155-C-Lab11#1]
https://github.com/cbourke/CSCE155-C-Lab11/blob/985338b4fcaac0a1b9411e80aef6c7a5da94c82d/rss_utils.h#L25

**Comment by cbourke** [comment]
Should be resolved with 2f9752e (which is still RSS2).

**Comment by hbiede** [comment]
Still seg faults. Crashes on rss_utils.c:22 because the getContent(s.url) on runRss.c:27 returns an empty string ![GDB](https://i.imgur.com/Vgm1GE5.png)

**Comment by cbourke** [comment]
Okay, try 2.0: aadfb96

**Comment by hbiede** [comment]
Well, we've delayed the segfault. It now makes it one line further before segfaulting when trying to get the children in the loop ![GDB-2](https://i.imgur.com/k2fqanu.png)

**Comment by cbourke** [comment]
I'm seeing ZERO differences in the actual raw XML structure returned from both rss feeds (both same version, same structure) but libxml is treating them differently for some reason. I've added some code to check if there are children or just a "last" and it works on both but I don't know if it is future proof or not.

**Comment by hbiede** [comment]
I can't actually get anything to download still. Setting a breakpoint on writefunc never stops the process at all when running in GDB, so there is still something prohibiting (at least my instance) from downloading any text, so your if statement isn't helping at all for me because rootNode is null.

**Comment by cbourke** [comment]
From a clean clone (in temp in the cse155e home dir), everything is working fine.  I added the debug flag and was able to step and see the raw xml and the root node was not null...

**Comment by hbiede** [comment]
Must've missed something in transcribing your commits. Solved for me too
